### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by tolleiv** [AOEpeople/gitlab-crucible-bridge#2]
When operating the service, it would be nice to see how many incoming calls are processed per timeslot and how many of them matched a given project. For that purpose it would be nice to have prometheus instrumentation built in to generate metrics and provide them for monitoring and alerting.

**Comment by Dbzman** [comment]
Would something like this be sufficient?

- gitlab_crucible_bridge_requests_total (Number of incoming webhooks)
- gitlab_crucible_bridge_requests_success (number of successfully triggered syncs)
- gitlab_crucible_bridge_requests_not_found (number of calls where no project was found)
- gitlab_crucible_bridge_requests_failed (number of calls which failed due to other reasons)

**Comment by carstenlenz** [comment]
`gitlab_crucible_bridge_requests_total` is completely sufficient for your proposed metrics.
The latter three are just variations of the first and you can differentiate them with labels or one label here (e.g. `outcome=<success|not_found|failure>`)

**Comment by carstenlenz** [comment]
Maybe add a histogram `gitlab_crucible_bridge_request_duration_seconds`. 
If you add the above proposed label then you get your proposed metric (via `gitlab_crucible_bridge_request_duration_seconds_count`) and also timings.

**Comment by Dbzman** [comment]
Thanks, that sounds good! Seems like I should dive deeper into prometheus. Didn't know about the labels. 🙈

**Comment by Dbzman** [comment]
Added in version 1.1.0
