### ISSUE TITLE
gitlab-crucible-bridge fails to login to Crucible

### ISSUE THREAD

**Issue by felippeduran** [AOEpeople/gitlab-crucible-bridge#3]
Hi,

I'm having trouble starting the gitlab-crucible-bridge. It keeps giving me this error:

```
2018-07-26T12:37:22.439Z gitlab-crucible-bridge[gitlab-crucible-bridge-cmd-57df4467-6qqd4]: panic: invalid character '<' looking for beginning of value
2018-07-26T12:37:22.439Z gitlab-crucible-bridge[gitlab-crucible-bridge-cmd-57df4467-6qqd4]: goroutine 1 [running]:
2018-07-26T12:37:22.439Z gitlab-crucible-bridge[gitlab-crucible-bridge-cmd-57df4467-6qqd4]: main.(*CrucibleSettings).updateCachedProjects(0xc42016c000)
2018-07-26T12:37:22.439Z gitlab-crucible-bridge[gitlab-crucible-bridge-cmd-57df4467-6qqd4]: 	/go/src/github.com/aoepeople/gitlab-crucible-bridge/crucible.go:56 +0x817
2018-07-26T12:37:22.439Z gitlab-crucible-bridge[gitlab-crucible-bridge-cmd-57df4467-6qqd4]: main.main()
2018-07-26T12:37:22.439Z gitlab-crucible-bridge[gitlab-crucible-bridge-cmd-57df4467-6qqd4]: 	/go/src/github.com/aoepeople/gitlab-crucible-bridge/server.go:107 +0x2ee
```

It seems that it fails during login to Crucible.

```
=== gitlab-crucible-bridge Config
CRUCIBLE_API_BASE_URL                  http://crucible.mydomain.com/cru/rest-service-fecru
CRUCIBLE_API_KEY                       XXXXXXXXXXXXXXXXXXXXXXXX
CRUCIBLE_PASSWORD                      XXXXX
CRUCIBLE_PROJECT_LIMIT                 1000
CRUCIBLE_PROJECT_REFRESH_INTERVAL      60
CRUCIBLE_USERNAME                      XXXXXX
GITLAB_TOKEN                           XXXXXXXXX
PORT                                   80
```

When I try to make a POST to the same URL with curl, I keep getting an 404 error in html format. Probably this invalid character '<' is because of that, but I'm not sure. How can I know that the base URL I'm using is correct and that the REST API from Crucible is working properly?

My Crucible version is: `4.4.1 Build:20170515065843`

Thanks in advance!

**Comment by Dbzman** [comment]
Hey there,
you are right. The bridge cannot parse the HTML here. It looks like the base url is not properly configured. Since I am not that deep into Crucible and I heavily struggled with getting to know the right url during development, the example I gave in the readme is based on our configuration. It seems that the "cru" part in the url is the "context" which is configurable and may diverge from your installation.
https://developer.atlassian.com/server/fisheye-crucible/rest-api-guide/
> webcontext is the webcontext under which FishEye/Crucible is hosted (as configured in the <web-server context=""/> element in the application’s config.xml

Can you check what's configured there and change the base url accordingly? :)

**Comment by felippeduran** [comment]
Thanks for the reply Dbzman!

My web context was not set indeed. However, I've changed it to match the URL and I'm still getting the same error. I've done that by going to Administration > Server Settings > Web context.

My current settings are `<web-server context="crucible"/>` and

```
CRUCIBLE_API_BASE_URL                  http://crucible.mydomain.com/crucible/rest-service-fecru
```

I'm also trying to mimic the gitlab-crucible-bridge with this command:
```
curl -i -X POST --user username:password http://crucible.mydomain.com/crucible/rest-service-fecru/auth/login
```

The Site URL is also not set, but it is using http://crucible.mydomain.com as default.

Is there something else that I might be missing?

**Comment by Dbzman** [comment]
Hey @felippeduran 
I tried it again on our instance and got the same results. Then I noticed I forgot to set the `CRUCIBLE_USERNAME` and `CRUCIBLE_PASSWORD` environment variable while testing. Looks like the login method does not properly handle failed logins. I'll fix that. It's probably not the issue in your case but I just noticed that. ;)
Regarding your issue: Does the user you use for login has admin permissions? The bridge uses the /admin/repositories endpoint to trigger the sync.
Also if you use curl make sure that you use `application/x-www-form-urlencoded`
https://docs.atlassian.com/fisheye-crucible/latest/wadl/fecru.html#rest-service-fecru:auth:login

**Comment by felippeduran** [comment]
I've managed to make it work. It seems that I've tried lots of different URL combinations except the one that did work: `crucible.mydomain.com/rest-service-fecru`. Once I got this right, I also had to change the exposed port to 8888, which is the one you use in `server.go`. Now the hooks are working properly.

I have one last question though, is it possible to automatically create a code review in Crucible with a merge request System Hook?

**Comment by Dbzman** [comment]
Nice to hear that it works! :)

The bridge does not have this feature and I didn't plan to implement it since we don't use merge requests in our workflow. If you want to implement something, feel free to open a PR. At least creating reviews for branches, as opposed to picking every single commit, is quite easy in Crucible. It also supports updating the review automatically on push.
But technically it should be quite straightforward to implement something like that.

I'll close this issue since you got it to work.
